---
# handlers file for kibatic.traefik
- name: Reload traefik unit
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
    enabled: true
  when: traefik_manage_service
