---

- name: Converge
  hosts: all
  roles:
    - role: ansible-traefik
  vars:
    traefik_update: true
    traefik_binary_url: "https://github.com/containous/traefik/releases/download/v2.0.2/traefik_v2.0.2_linux_amd64.tar.gz"
    traefik_template: "traefik.yml"
    traefik_config_file: "/etc/traefik.yml"
    traefik_dynamic_configs:
      - src: "traefik-dynamic.yml"
        dest: "/etc/traefik-dynamic.yml"
