---

scenario:
  name: version2
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8
    command: /sbin/init
    privileged: true
    published_ports:
      - 0.0.0.0:9999:80/tcp
provisioner:
  name: ansible
verifier:
  name: testinfra
