---

scenario:
  name: default
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - idempotence
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug
verifier:
  name: testinfra
